import {Unna } from 'next/font/google'
import './globals.css'

const unna = Unna({ weight:['400', '700'], subsets: ["latin"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={unna.className}>{children}</body>
    </html>
  )
}
